version: "3.1"
services:
  nacos:
    image: nacos/nacos-server:1.4.0
    container_name: nacos
    ports:
      - "8848:8848"
      - "9555:9555"
    restart: always
    environment:
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: imjcker.synology.me
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: mysql


